let answers = [];
let currentScore = 0;
let quiz = [];
let randomQuestion;

  quiz[0] = new Question("1. A Digital Developer has been given a specification to integrate with a REST API for retrieving weather conditions. The service expects parameters to be form encoded. Which service type should the Developer register?", "HTTP Form", "SOAP", "FTP", "WebDAV");
  quiz[1] = new Question("2. What happens if the log file size limit is reached in custom logging?", "Logging is suspended for the day.", "Logging is suspended for two hours.", "The log file is deleted and recreated from scratch.", "The log file rolls over and the last used log is overwritten.");
  quiz[2] = new Question("3. Which line of code creates a content slot that can be included on homepage.isml to display on the home page?", "< isslot id='my_banner' description='for home page' context='global' >", "< isslot id='my_banner ' description='for home page' type='global' context='content' contextobject='${pdict.ContentSearchResult.content}' / >", "< isslot id='my_banner' description='for home page' type='global' context='homepage' / >", "< isslot id='my_banner ' description='for home page' context='global' contextobject='${pdict.CurrentHomePage}' / >");
  quiz[3] = new Question("4. A Digital Developer selects <em>'Show Orderable Products Only'</em> in the <em>Search > Search Preferences</em> Business Manager module. Which business goal does this accomplish?", "Exclude products from search results if Available to Sell (ATS) = 0.", "Exclude back-ordered products from showing on the website.", "Block displaying the product detail page if Available to Sell (ATS) = 0.", "Exclude pre-order products from search results.");
  quiz[4] = new Question("5. Universal Containers created a site export file from staging in the global export directory. How should the Digital Developer update their sandbox using this staging site export file?", "Use the Site Development > Site Import & Export Business Manager module.", "Perform a data replication from staging.", "Download the site export file and use UX Studio to transfer the data to the sandbox.", "Use the Site Development > Import & Export Business Manager module.");
  quiz[5] = new Question("6. A Digital Developer added a file named <em>MyBusinessController.js</em> in the cartridge named <em>app_project</em>. The project design calls for this new file to override <em>MyBusinessController.js</em> in <em>client_project</em>. The <em>client_project</em> cartridge contains other necessary functionality. Additional functionality is also included in the <em>storefront_core</em> and <em>storefront_controllers</em> cartridges. Which cartridge path meets the project requirements?", "app_project:client_project:storefront_controllers:storefront_core", "client_project:app_project:storefront_controllers:storefront_core", "app_project:storefront_controllers:storefront_core", "storefront_core:storefront_controllers:client_project:app_project");
  quiz[6] = new Question("7. A Digital Developer has detected storefront pages being rendered with an error message. After inspecting the log files, the Developer discovered that an enforced quota is being exceeded. What action should the Developer take to stop the quota violation?", "Change the Business Manager configuration for the quota settings.", "Rewrite the code that is causing the overage.", "Take no action, the overage will be resolved when concurrent visitors are reduced.", "Ask support to remove the quota limit.");
  quiz[7] = new Question("8. Universal Containers wants to add a model field to each product. Products will have locale-specific model values. How should the Digital Developer implement the requirement?", "Set the model field as a localizable attribute.", "Utilize resource bundles for translatable values.", "Store translated model values in different fields; one field for each locale.", "Add model to a new custom object with localizable attributes.");
  quiz[8] = new Question("9. A Digital Developer must resolve a performance issue with product tiles. The Developer determines that the product tiles are NOT being cached for a long enough period. Which two methods can the Developer use to verify the cache settings for the product tiles? (Choose 2 answers):", "Enable cache information in the storefront toolkit and view the cache information for the product tile.<br/>View the product list page cache settings provided in the Administration > Manage Sites Business<br/>", "View the cache information provided by the Merchant Tools > Technical Reports Business Manager module. <br/> Enable cache information in the storefront toolkit and view the cache information for the product tile.", "Enable the template debugger to verify the cache times for the producttile.isml template. <br/> Enable cache information in the storefront toolkit and view the cache information for the product tile.", "Enable the template debugger to verify the cache times for the producttile.isml template. <br/> View the product list page cache settings provided in the Administration > Manage Sites Business");
  quiz[9] = new Question("10. A Digital Developer is working on a multi-site realm. A new site requires a different layout for the account landing page. The business logic and data model remain the same. The existing code is in <em>AccountControl.js</em> and <em>accountlanding.isml</em> in the <em>app_storefront cartridge</em>. The <em>app_storefront cartridge</em> contains code for all other business functions. The cartridge path for the new site is currently <em>int_cybersource:int_paypal:app_storefront</em>. The Developer creates a new cartridge named <em>app_newsite</em> that contains only the <em>accountlanding.isml</em> template for the new site. Which modification should be made to the new cartridge path?", "Set the cartridge path to that app_newsite is before app_storefront.", "Set the cartridge path to that app_storefront is before int_cybersource.", "Set the cartridge path to include only app_newsite.", "Set the cartridge path to that app_newsite is after app_storefront.");
  quiz[10] = new Question("11. A Digital Developer creates a B2C Commerce server connection in their UX Studio workspace. The Developer adds new cartridges to the workspace, but the cartridges do NOT execute as the Developer expects. Which three things should the Digital Developer verify to ensure the cartridges are uploaded? (Choose three.)", "The Auto-Upload setting is enabled for the server connection.<br/>The cartridge is for the current version of B2C Commerce. <br/> The server is configured to accept incoming connections.<br/>", "The Active Server setting is enabled for the server connection. <br/> The server is configured to accept incoming connections. <br/> The credentials for the server connection are correctly entered.", "The credentials for the server connection are correctly entered. <br/> The server is configured to accept incoming connections. <br/> The Auto-Upload setting is enabled for the server connection.", "The Auto-Upload setting is enabled for the server connection. <br/> The Auto-Upload setting is disabled for the server connection. <br/> The server is configured to accept incoming connections.");
  quiz[11] = new Question("12. Universal Containers specifies a new category hierarchy for navigating the digital commerce storefront. A Digital Developer uses Business Manager to manually create a catalog with the specified category hierarchy, then uses the <em>Products & Catalogs > Import & Export</em> module to export the catalog as a file. How can other Developers with sandboxes on the same realm create the same catalog in their own sandboxes?", "Use Business Manager to upload and import a copy of the export file obtained from the original Developer.", "Use the remote upload capability of the Site Import & Export module of Business Manager.", "Use the import capability of the Site Import & Export module of Business Manager.", "Use the Business Manager Data Replication module to replicate the catalog from the original Developer's sandbox.");
  quiz[12] = new Question("13. The following code ensures that an address ID CANNOT be used if it is already in use by another address in the customer's address book. There is a problem with the code. The error message for an invalid address ID is never shown to the user on the form field<br/><br/><pre>if (address.ID !== addressForm.addressid.value) {<br/> for (var i = 0; 1 < addressBook.addresses.length; i++) {<br/>  if (addressBook.addresses[i].ID === addressForm.addressid.value) {<br/>   addressForm.invalidateFormElement();<br/>   throw new Error('Address name already exists');<br/>   }<br/>  }<br/>}</pre><br/><br/>How should the Digital Developer resolve this issue so that the error message is displayed on the address ID form field?", "addressForm.invalidateFormElement('addressid');", "addressForm.addresssid.invalidateFormElement = true;", "addressForm.invalidateFormElement(addressForm.addressid);", "addressForm.addresssid.invalidateFormElement();");
  quiz[13] = new Question("14. Given the file structure below, which ISML method call renders the customLandingPage template?:<br/><br/> <em>content > custom > customLandingPage.isml</em>", "ISML.renderTemplate('content/custom/customLandingPage');", "ISML.renderTemplate('cartridge/templates/default/content/custom/customLandingPage');", "ISML('content/custom/customLandingPage');", "ISML.render('content/custom/customLandingPage');");
  quiz[14] = new Question("15. A business user wants to add a link to a content page from within the body of another content asset. The target content asset ID is: <em>terms-and-conditions</em>. Which link function generates the correct link?", "$httpUrl('Content-Show', 'cid', 'terms-and-conditions')$", "$include('Page-Include', 'cid', 'terms-and-conditions')$", "$http('Content-Page', 'cid', 'terms-and-conditions')$", "$url('Page-Show', 'cid', 'terms-and-conditions')$");
  quiz[15] = new Question("16. Why should a Digital Developer use ProductSearchModel.getProducts() instead of Category.getOnlineProducts() to access products?", "It reduces accesses to the application server.", "It is more readable code.", "It has fewer lines of code.", "It uses the search index.");
  quiz[16] = new Question("17. A Digital Developer is adding support for an additional language other than the default. The locale code for the new language is de. In which folder should the developer place resource bundles?", "templates/resources", "templates/de", "templates/default", "templates/default/resources");
  quiz[17] = new Question("18. Assume the code below is executing: <br/><br/><pre>var log = Logger.getLogger('xyz', 'export');<br/>log.info('This is important information)</pre><br/> Business Manager has the configuration:<br/>Active Log category is 'root' with log level of 'info.'<br/>Given this information, what is the beginning of the filename in which the log will be written?", "custom-xyz", "xyz", "custominfo-blade", "custom-export");
  quiz[18] = new Question("19. A Digital Developer wants pass control to an ISML template from a JavaScript Controller and load product on the pipeline dictionary with the name myProduct. Which code sample will achieve this?", "ISML.renderTemplate ( 'helloworld.isml', { 'myProduct': 'product' });", "ISML.renderTemplate ( 'helloworld.isml', { 'product': myProduct });", "ISML.renderTemplate ( 'helloworld.isml', { product: myProduct });", "ISML.renderTemplate ( 'helloworld.isml', { myProduct: product });");
  quiz[19] = new Question("20. A Digital Developer has identified that the code segment below is causing performance problems.<br/><br/><pre>var productSearchHits : Iterator = pdict.SearchResult.getProducts();<br/>var foundProduct : dw.catalog.Product;<br/>var results = new ArrayList();<br/><br/>while (productSearchHits.hasNext()) {<br/> foundProduct = productSearchHits.next();<br/><br/> if (foundProduct.custom.isOnSaleFlag == 'true') {<br/>  results.add(foundProduct);<br/> }<br/>}<br/><br/>return results;</pre><br/>What should the Developer do to improve the code?", "Breaks the process into separate loops.", "Use a system attribute instead of the isOnSaleFlag custom attribute.", "Avoid post-processing and use the isOnSaleFlag attribute as a search refinement.", "Avoid using an Iterator and use a Collection instead.");
  quiz[20] = new Question("21. Universal Containers has expanded its implementation to support German with a locale code of <em>de</em>. The current resource bundle is <em>checkout.properties</em>. To which file should the developer add German string values?", "checkout_de.properties in resources folder", "checkout.properties in the de locale folder", "checkout.properties in the default locale folder", "de_checkout.properties in resources folder");
  quiz[21] = new Question("22. A Digital Developer has a new requirement to disable the 'Discover' credit card type for all checkouts. What does the Developer need to change in Business Manager to fulfill this requirement?", "Credit cards in the Merchant Tools > Ordering > Payment Methods module.", "Checkout exclusion rules in the Merchant Tools > Site Preferences > Checkout Preferences module.", "Credit card exclusion rules in the Merchant Tools > Site Preferences > Payment Preferences module.", "Credit card exclusion rules in the CreditCardType.json configuration file.");
  quiz[22] = new Question("23. A Digital Developer needs to store information temporarily and decides to create a custom object. Which code creates a custom object?", "CustomObjectMgr.createCustomObject(CustomObjectType,primaryKey)", "CustomObject.createCustomObject(CustomObjectType,primaryKey);", "CustomObject.createCustomObject(primaryKey,CustomObjectType);", "CustomObjectMgr.createCustomObject(primaryKey);");
  quiz[23] = new Question("24. The following sample code is NOT providing the desired results. The Digital Developer needs to add an entry to the logs to debug the problem. <br/><br/><br/><pre>var paymentInstruments = order.getPaymentInstruments(PaymentInstrument.METHOD_DW_APPLE_PAY).toArray();<br/><br/>if (!payment.Instruments.length) {<br/> // Log Error Message <br/> return null;<br/>}<br/><br/>var paymentInstrument = paymentInstruments[0];<br/>var paymentTransaction = paymentInstrument.getPaymentTransaction();</pre><br/><br/> Which statement correctly adds a log entry?", "Logger.error('Unable to find Apple Pay payment instrument for order.'+paymentInstruments);", "Logger.exception('Unable to find Apple Pay payment instrument for order.'+paymentInstruments);", "Logger.getErrorLog().log('Unable to find Apple Pay payment instrument for order.'+paymentInstruments);", "Logger.fault('Unable to find Apple Pay payment instrument for order.'+paymentInstruments);");
  quiz[24] = new Question("25. Universal Containers wants to give customers the ability to refine product search results by a product custom attribute, <em>weightCapacity</em>. Which series of steps should a Digital Developer take to show this refinement on the storefront?", "Define a search refinement for weightCapacity, then rebuild the product search index.", "Define a sorting rule for weightCapacity, then rebuild the product search index.", "Define search-suggestion buckets for weightCapacity, then rebuild the product search index.", "Define a search refinement for weightCapacity, then clear the page cache segment for SearchShow.");
  quiz[25] = new Question("26. A Digital Developer needs to check for product inventory in a specific inventory list using the Open Commerce API. An example request URL is:<br/><br/><pre>http://sitegenesis.demandware.net/dw/data/v18_3/inventory_lists/ecom-inventory/product_inventory_records/00883408601</pre><br/>Which <em>resource_id</em> value enables the appropriate resource?", "/inventory_lists/**", "/inventory_lists/*", "/inventory_list_search", "/products/*");
  quiz[26] = new Question("27. Which three techniques improve client-side performance in production while following documented best practices? (Choose three.)", "Use one style sheet for each ISML decorator template.<br/>Compress CSS<br/>Use inline Javascript.<br/>", "Place CSS outside of templates. <br/>Use one style sheet for each ISML decorator template.<br/>Combine several images into a single image.", "Combine several images into a single image. <br/>Place CSS outside of templates. <br/> Place js outside of templates.", "Combine several images into a single image. <br/>  Minimize css and js. <br/>  Place CSS outside of templates.");
  quiz[27] = new Question("28. A Digital Developer needs to add logging to the following code: <br/><br/><pre>var Logger = require('dw/system/Logger');<br/><br/>var urlEmail = 'https://api.weibo.com/2/account/profile/email.json' + accesTokenSuffix; <br/><br/>http.open('GET', urlEmail); <br/>http.send();<br/><br/>var resultEmail = http.getText();<br/><br/>if (200 !== http.statusCode) {<br/> // Log Invalid Status Code<br/>}</pre><br/><br/> Which statement logs the HTTP status code to a debug-level custom log file?", "Logger.getLogger('profile').debug('Error retrieving profile email, Status Code: {0} was returned.', http.statusCode);", "logger.getLogger('profile').debug('Error retrieving profile email, Status Code: ', http.statusCode);", "logger.debug('Error retrieving profile email, Status Code: {0} was returned.', http.statusCode);", "Logger.getLogger().debug('Error retrieving profile email, Status Code: {0} was returned.', http.statusCode);");
  quiz[28] = new Question("29. Which three object types can a developer import using the <em>Merchant Tools > Content > Import & Export</em> module in Business Manager? (Choose three.)", "Content slots<br/>Folders<br/>Content assets<br/>", "Content slots <br/> Images and other static assets <br/> Content assets", "Products <br/> Categories <br /> Content slots", "Folders <br/> Products <br/> Categories");
  quiz[29] = new Question("30. Universal Containers recently completed updates to their storefront shopping cart page. A problem has been discovered since the update. Users are no longer able to submit coupon codes on this page. Additionally, authenticated users who try to add a coupon are logged out. The following processing code is found in the <em>Cart.js</em> controller file:<br/><br/><pre>function (formgroup) {<br/> var CSRFProtection = require('dw/web/CSRFProtection');<br/><br/> if (!CSRFProtection.validateRequest()) {<br/>  app.getModel('Customer').logout();<br/>  app.getView().render('csrf/csrffailed');<br/>  return null;<br/> }<br/><br/> var result = {cart: cart, EnableCheckout: true, dontRedirect: true};<br/><br/> if (formgroup.couponcode.htmlValue) {<br/>  var status = cart.addCoupon(formgroup.couponCode.htmlValue);<br/>  // Update result with status of coupon<br/> } else {<br/>  result.CouponError = 'COUPON_CODE_MISSING';<br/> }<br/> return result;<br/>}</pre><br/>What should the Developer verify to identify the issue?", "The CSRF token is present in the form and is being submitted in the request.", "The CSRF cartridge is included in the site's cartridge path.", "The form group has the secure attribute set to true.", "The CSRF settings in Business Manager are properly configured.");
  quiz[30] = new Question("31. A Digital Developer wants to selectively retrieve products and process them from an iPhone. Which action should the Developer take, given that JavaScript controllers CANNOT be used?", "Use WebDAV Client to retrieve products.", "Use import/export in Business Manager.", "Create a webservice to retrieve products.", "Use OCAPI and invoke it in native language.");
  quiz[31] = new Question("32. A Digital Developer must give users the ability to choose an occasion (holiday, birthday, anniversary, etc.) for which gifts are currently being selected. The data needs to be persistent throughout the current shopping experience. Which data store variable is appropriate, assuming there is no need to store the selection in any system or custom objects?", "Session scope variable", "Request scope variable", "Page scope variable", "Content slot variable");
  quiz[32] = new Question("33. A Digital Developer suspects a logical error in a script. Which action will help locate the error?", "Check request logs for evidence of the logical error.", "Submit a support ticket to B2C Commerce.", "Put breakpoints in the code, debug, and examine variable values.", "Print all values in the script node called before the current script.");
  quiz[33] = new Question("34. Once the Cache Information tool of the storefront toolkit is enabled, how can a Digital Developer view caching information for a particular component of the page?", "Hover over the caching icons now present on the storefront.", "Open the Request Logs to view the caching information.", "Start a pipeline debugging session and view the caching information provided.", "Right-click on the component in UX Studio and view the caching properties of the file.");
  quiz[34] = new Question("35. A Digital Developer is working in a sandbox on a site named <em>test-site</em> using the domain <em>test.demandware.net</em>. The Developer needs to compile a url to make an Open Commerce API (OCAPI) request that returns product information. By default, which URL format is a proper Open Commerce API for Sandbox?", "https://test.demandware.net/s/test-site/dw/shop/v18_3/products/M1355?client_id=aaa...", "https://test.demandware.com/dw/shop/products/M1355?client_id=aaa...", "https://www.test.com/s/test-site/sfc/shop/products/M1355?client_id=aaa...", "https://www.test.com/dw/shop/v18_3/products/M1355?client_id=aaa...");
  quiz[35] = new Question("36. A Digital Developer needs to add a new form to the shopping cart page to allow customers to enter their rewards pass ID. There is already an existing Cart.js controller that handles processing of the other cart forms. In addition, a form field node is in the form XML and the necessary form input is present in the ISML template. The code below is the submit button for the ISML markup.<br/><br/><pre>< button type='submit' value='${pdict.CurrentForms.cart.addRewardPass.htmlName}' name='${pdict.CurrentForms.cart.addRewardPass.htmlName}' ><br/> ${Resource.msg('rewards.apply', 'locale', null)}<br/>< /button ></pre><br/><br/>What additional steps must occur before the Digital Developer can begin writing the processing code for this request?", "<ul><li>Add an < action /> node to the form definition XML with the attribute formid='addRewardPass'</li><li>Add the key addRewardPass, with a processing function as a value, to the object passed to the Form.handleAction() method in the Cart.js controller.</li></ul>", "<ul><li>Add an < submit /> node to the form definition XML with the attribute formid='addRewardPass'</li><li>Add the key addRewardPass, with a processing function as a value, to the object passed to the Form.handleAction() method in the Cart.js controller.</li></ul>", "<ul><li>Add the attribute addtl-form-action='addRewardPass' to the ISML form</li><li>Add the key addRewardPass, with a processing function as a value, to the object passed to the Form.handleAction() method in the Cart.js controller.</li></ul>", "<ul><li>Add an < action /> node to the form definition XML with the attribute formid='addRewardPass'</li><li>No change to Cart.js controller required.</li></ul>");
  quiz[36] = new Question("37. Universal Containers is preparing their storefront to use Open Commerce APIs (OCAPI). To which hook should the Digital Developer move taxation logic to ensure consistent order totals within B2C Commerce?", "dw.ocapi.shop.basket.calculate", "dw.ocapi.shop.order.validateOrder", "dw.ocapi.shop.basket.afterPostShipment", "dw.ocapi.shop.order.afterPOST");
  quiz[37] = new Question("38. A digital instance has one site, with one master product catalog separate from the site catalog. Some, but NOT all, products in the master catalog are assigned to categories of  the site catalog. Using Business Manager, how can a Digital Developer create a catalog export file that contains only the products assigned to the site catalog?", "Use the Catalog Export module to export the master catalog, with a category-assignment search to export specific products.", "Use the Catalog Export module to export the site catalog.", "Use the Site Import & Export module to export both the site catalog and the master catalog in a single archive.", "Use the Site Import & Export module to export the master catalog, filtered by site catalog categories to export specific products.");
  quiz[38] = new Question("39. A Digital Developer is asked to optimize controller performance by lazy loading scripts as needed instead of loading all scripts at the start of the code execution. Which statement should the Developer use to lazy load scripts?", "require () method", "importPackage () method", "$.ajax () jQuery method", "local include");
  quiz[39] = new Question("40. A Digital Developer is inspecting the weekly service status report for a critical internally-hosted web service used in the application and notices that there are too many instances of unavailability. Which two solutions are possible options to reduce the unavailability of the service? (Choose two.)", "Change the code that makes the request to set the throwOnError attribute, of the service, to be true.<br/> Increase the web service time out.<br/>", "Increase the web service time out. <br/>Modify the code that makes the request to the external service to be wrapped in a try / catch block.", "Update the external service to have a faster response time <br/>Increase the web service time out.", "Update the external service to have a faster response time  <br/> Modify the code that makes the request to the external service to be wrapped in a try / catch block.");
  quiz[40] = new Question("41. A job executes a pipeline that makes calls to an external system. Which two actions prevent performance issues in this situation? (Choose two.)", " Configure a timeout for the script pipelet. <br/> Disable multi-threading. <br/>", "Use synchronous import or export jobs<br/>Disable multi-threading.", "Use asynchronous import or export jobs.<br/>Disable multi-threading.", "Configure a timeout for the script pipelet.<br/>Use synchronous import or export jobs");
  quiz[41] = new Question("42. Universal Containers sells physical gift cards for the holidays. What needs to occur to guarantee the cards will always be available?", "Create an inventory record with Backorder Handling enabled.", "Create an inventory record with an unlimited Allocation value.", "Create an inventory record with an extremely high Allocation value (i.e., 1 billion certificates).", "Create a perpetual inventory record.");
  quiz[42] = new Question("43. Universal Containers wants to associate a region code value with an order to indicate the general area of its destination. This region code must be accessible whenever the order history is displayed. What is required to accomplish this?", "Define a custom attribute on the Order system object type to store the region code value.", "Store the region code value in a session variable.", "Define a custom object type to store the username with the region code.", "Store the region code value in the geolocation system attribute of the Order.");
  quiz[43] = new Question("44. A Digital Developer is requesting product information for an external integration. The following Open Commerce API (OCAPI) request is NOT functioning correctly:<br/><br/><pre>POST /dw/shop/v18_3/products/(creative-zen-v,namco-we-ski-wii)?client_id=aaaa...<br/>HTTP/1.1 Host: example.com</pre><br/><br/How should the Developer change the request?", "Change the HTTP method to GET.", "Change the URI to /dw/shop/v18_3/products/creative-zen-v.", "Change the HTTP method to PUT.", "Include an authentication token in the request.");
  quiz[44] = new Question("45. A Digital Developer has been given a requirement to add fault tolerance to an existing web service integration that uses Service Framework. Administrators at Universal Containers need to be able to configure the timeout and rate limiting. Which approach should the Developer use to implement the requirement?", "Implement a ServiceUnavailableException exception handler to execute fallback code.", "Implement a condition that checks to see if the response was empty and execute fallback code if true.", "Create a site preference to store timeout settings and implement an IOException handler to execute fallback code.", "Use the setTimeout method to execute fallback code if the request has NOT completed.");
  quiz[45] = new Question("46. A Digital Developer noticed that cartridges in their workspace are NOT executing. The Developer confirms that the cartridges are uploaded to the B2C Commerce server connection's target version directory. Which action potentially solves this problem?", "Set the server connection's target version directory to the active code version.", "Set the active code version to use the latest compatibility mode.", "Remove invalid characters from the code version's name.", "Remove invalid characters from cartridge file and folder names.");
  quiz[46] = new Question("47. A Digital Developer is implementing an Open Commerce API call to add products to a basket. Given the following resource configuration: <br/><br/><pre>{<br/> 'resource_id': '/baskets/**',<br/> 'methods': ['get'],<br/> 'read_attributes': '(**)',<br/> 'write_attributes': '(**)'<br/>}</pre><br/><br/Which modification allows the requests to successfully execute?", "Change the 'resource_id' value to: '/baskets/*/items'.", "Change the 'methods' value to: ['get', 'post'].", "Change the 'write_attributes' value to: '(+items)'.", "Change the 'read_attributes' value to: '(items)'.");
  quiz[47] = new Question("48. Which two methods are efficient and scalable? (Choose two.)", "ProductSearchModel.getProductSearchHits() <br/> Category.getProducts() <br/>", "ProductMgr.queryAllSiteProducts() <br/> ProductSearchModel.getProductSearchHits()", "ProductSearchHit.getRepresentedProducts()<br/>ProductSearchModel.getProductSearchHits()", "Category.getProducts()<br/>ProductMgr.queryAllSiteProducts()");
  quiz[48] = new Question("49. Universal Containers calls the following combination of products 'The Basics' and sells the combination as a unique product ID: <br/><br/>One Model 103 container, <br/>Five Model 611 container, <br/>Tree Model 201 container. <br/><br/>The Developer created these three products in the catalog. <br/>What is the next step in Business Manager to create 'The Basics' as a combination?", "In the Products module, create a product named 'The Basics' and add the products to the Product Bundles tab.", "In the Product Bundles module, create a bundle named 'The Basics'.", "In the Products module, create a product named 'The Basics' and add the products to the Product Sets tab.", "In the Product Sets module, create a product set named 'The Basics'.");
  quiz[49] = new Question("50. A Digital Developer extends a system object, Product, and adds a Boolean attribute, 'sellable,' to it. Assuming 'prod' is the variable name handling the product, what code can the Developer use to access it?", "prod.custom.sellable", "prod.extended.sellable", "prod.sellable", "prod.persistable.sellable");
  quiz[50] = new Question("51. A Digital Developer is tasked with setting up a new Digital Server Connection using UX Studio in their sandbox. Which three items are required to accomplish this task? (Choose three.)", " Instance Hostname <br/> Business Manager Username <br/> Business Manager Password <br/>", "Instance Version <br/> Instance Hostname <br/> Instance Hostname Manager", "Keystore Password <br/> Business Manager Username <br/> Instance Version", "Keystore Password <br/> Instance Version <br/> Instance Manager");
  quiz[51] = new Question("52. A Digital Developer adds the following line of code to a script. <br/><br/><pre>dw.system.Logger.getLogger('login').debug('Login API has succeeded')</pre><br/><br/> The code executes without error; however, the log file on disk does NOT contain the log message. Which two actions should be completed to write the log message to disk? (Choose two.)", "Ensure that the debug log level is enabled to write to file in the Custom Log Settings Business Manager module. <br/> Archive old log files to make room in the log directory. <br/>", "Ensure that the 'login' category is added to the Custom Log Filters in the Log Settings Business Manager module. <br /> Ensure that the debug log level is enabled to write to file in the Custom Log Settings Business Manager module.", "Ensure that the debug log level has been added to the custom log level types in the Global Preferences business manager module.<br/>Ensure that the 'login' category is added to the Custom Log Filters in the Log Settings Business Manager module.", "Archive old log files to make room in the log directory. <br/> Ensure that the debug log level has been added to the custom log level types in the Global Preferences business manager module.");
  quiz[52] = new Question("53. Which technical reports datapoint measures the performance of a controller's script execution if network factors and Web Adaptor processing is ignored?", "Processing time", "Cache hit ratio", "Call count", "Response time");
  quiz[53] = new Question("54. Universal Containers needs to have Apple Pay disabled for the country of Spain. Which Business Manager module should the Developer use to meet this requirement?", "Merchant Tools > Ordering > Payment Methods", "Merchant Tools > Site Preferences > Apple Pay", "Merchant Tools > Ordering > Payment Processors", "Merchant Tools > Site Preferences > Payment Types");
  quiz[54] = new Question("55. A Digital Developer has created a new PaymentForm controller that requires communication with the server and must be made using the HTTPS protocol. Which code sample should the Developer use to make sure that HTTPS is used?", "exports.PaymentForm = guard.ensure(['https', 'post', 'loggedIn'], handlePaymentForm);", "exports.PaymentForm = guard.ensure(['http', 'post', 'loggedIn'], handlePaymentForm);", "exports.PaymentForm = guard.expose(['post', 'loggedIn'], handlePaymentForm);", "exports.PaymentForm = guard.httpsPost(handlePaymentForm);");
  quiz[55] = new Question("56. Universal Containers requires that a new order comments attribute is added to the existing SiteGenesis checkout flow. This new attribute needs to be included as part of the standard order export. Aside from updating the HTML markup and form definition, which option contains all necessary steps to achieve this task?", "Modify the 'COPIaceOrder' controller to update a CSV file in the IMPEX WebDAV directory with the order ID and comments.<br/>Modify the order export process to read information in the CSV file and include it as part of the export.", "Add the new attribute to the 'Order' system object.<br/>Modify the 'COPIaceOrder' controller to add this new attribute to the current session's 'Order' object.", "Add the new attribute to the 'Customer' system object.<br/>Modify the 'COPIaceOrder' controller to add this new attribute to the current session's 'Customer' object.", "Create a new custom object type for order comments that contains the attributes: order ID and comments.<br/>Modify the 'COPIaceOrder' controller to create a new order comments custom object upon order completion.");
  quiz[56] = new Question("57. Which code sample is required to use a custom tag provided in SiteGenesis in an ISML template?", "< isinclude template='util/customtags' >", "< isinclude template='util/modules' >", "< isinclude url='${UTLUtils.url('CustomTag-Start')}' >", "< isscript > dw.util.CustomTagMgr.createCustomTag('mytag'); < / isscript >");
  quiz[57] = new Question("58. Universal Containers wants to change a content slot that is currently configured to display a content asset. Now they want the slot to display the top five selling boxes for the week. Which two changes need to be made for this to occur? (Choose two.)", "Change the slot's configuration content type to 'recommendations.' <br/> Change the slot's configuration template to the appropriate rendering template.", "Change the slot's configuration content type to 'products.' <br /> Change the slot's configuration content type to 'recommendations.'", "Delete the existing content asset. <br/>Change the slot's configuration content type to 'products.", "Change the slot's configuration content type to 'products. <br/>Change the slot's configuration content type to 'recommendations.");
  quiz[58] = new Question("59. A Digital Developer has a site export file on their computer that needs to be imported into their sandbox. How should the developer update their sandbox with the data in this file?", "Upload and import the file using the local option within the Site Import & Export Business Manager module.", "Connect and import the file using the remote option within the Site Import & Export Business Manager module.", "Upload the file to the Impex WebDAV directory and import using the Site Import tool within UX Studio.", "Upload the file to the Static WebDAV directory and import using the Import & Export Business Manager module.");
  quiz[59] = new Question("60. A Digital Developer is working on a project to convert a pipeline to a JavaScript controller. UX Studio has a functioning pipeline debugger configured for the site. Assume the Developer will add a breakpoint to the controller when it is written. What must be done in order to use the debugger with the new controller when it is written?", "Modify the debugger configuration and use the existing pipeline debugger.", "Create and use a new script debug configuration.", "Use the existing pipeline debugger.", "Create and use a new controller debug configuration.");
  quiz[60] = new Question("61. An instance has custom logging enabled. The log reaches the file size limit. What happens in this situation?", "Logging is suspended for the day", "The log file is deleted and a new log file is created.", "The current log file is archived and a new log file is created.", "The log file Rolls over and the oldest log messages are overwritten");
  quiz[61] = new Question("62. A developer has the following files in template/resources:<br/>account.properties<br/>weight.unit=kilos<br/>account_en.properties<br/>weight.unit=stones<br/>account_en_US.properties<br/>weight.unit= pounds.<br/>Using the default locale configuration, what is the current outcome of the page that renders the account.isml template snippet below when visiting the Sofrefront with the English for Canada(en_CA) locale= Your parcel weighs 10 ${Resource.msg('weight.unit','account')}", "Your parcel weighs 10 stones.", "Your parcel weighs 10 pounds.", "Your parcel weighs 10 undefined.", "Your parcel weighs 10 kilos");
  quiz[62] = new Question("63. A client has custom object definition and requirement that occasional data changes in staging also need to exist in production. Which task should the developer perform to meet these requirements when setting up the custom object?", "Create the custom object definition in staging as Replicable", "Create two copies of the custom object in staging and set Sharing = True.", "Create the custom object definition in staging as Shared", "Create the custom object definition in production as Replicable");
  quiz[63] = new Question("64. A developer is asked to write a log containing the ID and name of the product with a variable named myProduct. Which snippet of code should be used?", "Logger.warn('The current product is {0} with name {1}', myProduct.getID(), myProduct.getName());", "Logger.warn('The current product is {0} with name {1}'), context(myProduct.getID(), myProduct.getName());", "Logger.warn('The current product is ${myProduct.getID()} with name ${myProduct.getName()}');", "Logger.warn('The current product is %s with name %s'), context(myProduct.getID(), myProduct.getName());");
  quiz[64] = new Question("65. Business Manager has the configuration:<br/><ul><li>Active log category is 'root'</li><li>Log level of INFO.</li></ul> The code below executes:<br/><br/><pre>var log = Logger.getLogger('products','export');<br/>log.info ('This is important information');</pre><br/>Using this information, what is the beginning of the filename in which the log will be written?", "custom-products", "custom-export", "products", "info-export");
  quiz[65] = new Question("66. Given the requirements:<br/><ul><li>To integrate with an external web service using HTTP requests.</li><li>To create a service for this purpose with the Service framework using the <em>LocalServiceRegistry</em> class.</li><li>To test the service before the external service provider makes the API available.</li></ul>Which solution allows the developer to satisfy the requirements?", "Create a service and implement the mockFill callback and set the service mode to mock.", "Create a service and implement the mockfull callback and a sitepreference to enable or disable the mock response.", "Create a service and a Sitepreference that induce the service to respond witch a mock response using a conditional.", "Create two services, one mock and the real one, and a Sitepreference that enable the mock or the real one");
  quiz[66] = new Question("67. A developer needs to update the <em>package.json</em> file so that it points to the hock file for a cartridge, using the hooks keyword. Which snippets work correctly when added to the file?:", "{ 'hooks': './cartridge/scripts/hooks.json' }", "{ 'hooks': './scripts/hooks.json' }", "{ hooks: './cartridge/scripts/hooks.json' }", "{ hooks: ./scripts/hooks.json }");
  quiz[67] = new Question("68. Given the following snippet:<br/><br/><pre>Server.append( 'Show' , function (req, res, next))</pre><br/>According to SFRA, which two options shows a correct way to complete the code above in order to provide data to the response using a controller? Choose 2 answers", "res.render('/content/myPage',{ data: myDataObject }); next(); }); <br/> res.setViewData ({ data: myDataObject }); res.render('/content/myPage') next(); });", "res.viewData = { data: myDataObject }; res.render('/content/myPage'); next(); });", "res.setViewData ({ data: myDataObject }); res.render('/content/myPage') next(); });", "res.render('/content/myPage'); next(); }).append{( Data:myDataObject });");
  quiz[68] = new Question("69. Given the code snippet above, what should be added after this code so it can be used for page component display?", "Module.exports = server.exports();", "Base.render = render;", "Module.exports = render;", "Module.exports.render = render;");
  quiz[69] = new Question("70. A developer has a specification to integrate with a REST API for retrieving traffic conditions. The service expects parameters to be form encoded. Which service type should the developer register?", "HTTP Form", "HTML Form", "SOAP Form", "POST Form");
  quiz[70] = new Question("71. A developer needs to show only car accessories when shoppers use the search term car accessories and exclude technology accessories and household accessories. Given the above requirement, what is the recommended approach using the <em>Search Dictionaries Dashboard?</em>", "Create a Common Phrase Dictionary entry: car accessories. Use search mode Exact Match.", "Create a Synonym Dictionary entry: car accessories, household, technology. Use search mode Exact Match", "Create a Common Phrase Dictionary entry: car accessories, NOT household, NOT technology. Use search mode Exact Match.", "Create a Synonym Dictionary entry: car accessories, household, technology. Use search mode First Word.");
  quiz[71] = new Question("72. A merchant asks a developer to create a Cache Partition for the home page, so that when the home page is edited, only the home page is cleaned. Given the above requirement, where should the developer create that partition in Business Manager?", "Administration > Sites > Manage Sites > Site > Cache", "Operations > Site > Manage Sites > Cache", "Operations > Cache > Site", "Site > Site Preferences > Cache");
  quiz[72] = new Question("73. Given the following ISML example, how should a developer reference the product object in the current iteration of the basket?<br/><br/><pre>< isloop items='${pdict.Basket.products}' var='product' status= 'loopstatus' > … < /isloop ></pre>", "product", "pdict.Basket.products{loopstatus}", "loopstatus.product", "pdict.product");
  quiz[73] = new Question("74. A client that sells to multiple countries in Europe needs to disable Apple Pay for Denmark. Which Business Manager module is used to achieve this requirement?", "Apple Pay", "Locale Payments", "Payment Methods", "Payment Processors");
  quiz[74] = new Question("75. A developer set up a new site with <em>Taxation: Net.</em> However, the business requirements changed and the site now needs to be <em>Taxation:Gross</em>. The Business Manager interface does not give this option. Which sequence of steps is necessary to change the site to gross taxation?", "Create a new site with Taxation set to Gross, then delete the old site.", "Make sure that the developer has 'Administrator' Access, then change the Taxation setting to Gross", "Unlock the site preferences and then change the Taxation setting to Gross", "Change the global setting,'Enable Taxation Methods' to true, then change the Taxation setting to Gross");
  quiz[75] = new Question("76. <br /><pre>Server.get('Show', consentTracking.consent, cache.applyDefaultCache, function (req,res,next){<br/> var Site = require('dw/system/Syte');<br/> var pageMetaHelpter = require('*/cartridge scripts/helpers/pageMetaHelper');<br/> pageMetaHelpter.setPageMetaTags(req.pageMetaData, Site.current);<br/> res.render('/home/homePage');<br/> Missing code here<br/>}, pageMetadata computedPageMetadata);</pre><br/>The controller endpoint code snippet above does not work. Which line of code should the developer use to replace line 6 and correct the problem?", "next();", "return res;", "res.next();", "req.next();");
  quiz[76] = new Question("77. A developer is working on a new site for the U.S based on an existing Canadian site. One of the requirements is a change to the address form. The current Canadian form has an < options > list with the correct two-letter abbreviation for the provinces. The U.S. requirements are to:<ul><li>Have an < options > list with the correct two-letter abbreviation for the states in place of the province field.</li><li>Set the U.S site locale.</li><li>Add the options list field definition to the XML file.</li></ul>How should the developer set up the files before making the required edits?", "Create a new sub-folder in the forms folder. Name it en_US. Copy existing address.xml file", "Create a copy of existing address.xml file in the default folder. Rename that file to address_US.xml", "Create a new sub-folder in the forms folder. Name it US. Copy existing address.xml file in the new folder.", "Create a copy of existing address.xml file in the default folder. Rename that file to address_en_US.xml");
  quiz[77] = new Question("78. A merchant has a content slot on a page that currently displays products based on the top Sellers for the current week. They wish to change this functionality and, instead, have the slot render a specific content asset so that the content experience is more personalized to the visitors. Which two actions are necessary to make this change?. Choose 2 answers.", "Change the rendering template in the slot configuration <br/> Change the content type for the slot configuration <br/>", "Delete the existing content slot and create a new one. <br/> Change the default setting in the slot configuration", "Change the rendering template in the slot configuration <br/> Change the existing content slot and create a new one.", "Change the content type for the slot configuration <br/> Create a new one content slot.");
  quiz[78] = new Question("79. Given a file in a plug-in cartridge with the following code:<br/><br/><pre>'use strict':<br/>var base = module.superModule;<br/>function applyCustomCache (req,res,next){<br/> res.CachePeriod = 6; //eslint-disable-line no-param-reassign<br/> res.cachePeriodUnit = 'hours')//eslint-disable-line no-param-reassign<br/> next();<br/>}<br/>module.exports = base;<br/>module.exports.applyCustomCache = applyCustomCache;</pre><br/><br/>What does this code extend?", "A middleware script", "A controller", "A decorator", "A model");
  quiz[79] = new Question("80. A developer has custom debug statements in a script, but the messages are not showing up in the Storefront Toolkit Request Log. Which step needs to be completed to get the messages to appear in the Request Log?", "In Custom Log Settings, check the DEBUG box for Select Log Levels Written to Files.", "In Global preferences, check the box for Enable custom logging in Request Log.", "In Site Preferences, check the box for Enable custom Logging in Request Log", "In Custom Log Settings, activate the loggin category at DEBUG level.");
  quiz[80] = new Question("81. Below is a form definition snippet from the <em>newsletter.xml</em> file:<br/><br/><pre>< ?xml versión='1.0'? ><br/>< form xmlns=http://www.demandware.com/xml/form/2008-04-15 ><br/> < field formid='email' lavel='Email' type='String' mandatory='True' max-length='50' /><br/>< /form ></pre><br/>Which line of code creates a JSON object to contain the form data?", "Server.forms.getForm('newsletter');", "Server.form.getForm('dwfrm_newsletter')", "Server.form.getForm('newsletter');", "Server.forms.getForm('dwfrm_newsletter')");
  quiz[81] = new Question("82. A client wants to differentiate their monobrand stores with a special icon when shown in the store locator. The information is saved in a true/false custom attribute for each Store object in <em>Merchant Tools.</em> How should the developer follow SFRA best practices to expose this data for rendering?", "Use the module.superModule functionality and the call method to add a new property to the Store Model.", "Extend the existing Stores_Find controller with a new middleware function that performs the query", "Pass the Store system object to the template, so that custom properties are available", "Add an < isscript > to the template, and call StoreMgr.searchStoresByCoordinates();");
  quiz[82] = new Question("83. A merchant requires that an existing section of the Site become editable from the <em>Business Manager</em>, so that they can modify it independently of the developer. Which of these is an important factor for a developer to consider when choosing the appropriate solution between a content slot and a Page Designer component?", "Only content slot configurations can be tied to campaigns.", "Only Page Designer Components can be localized for different languages.", "Only page Designer components can be tied to campaigns.", "Only content slot configurations can ve localized for different languages.");
  quiz[83] = new Question("84. Given a job step configured in the <em>steptype.json</em>, a developer needs to add a custom status code <em>'NO_FILES_FOUND'</em>. Which code snippet will complete the requirement?", "var status = require('dw/system/status'); return new Status(Status.OK, 'NO_FILES_FOUND');", "var status = {success: 'OK'. Message: 'NO_FILES_FOUND'}; return status;", "this.status = 'NO_FILES_FOUND' return this;", "return 'NO_FILES_FOUND Explanation:");
  quiz[84] = new Question("85. Consider the following information:<br/><ul><li>A merchant has this three-tier category structure setup in the Storefront catalog: <em>New Arrivals > Women > Clothing</em></li><li>The category named <em>Clothing</em> has all the clothing items for Women and is merchandised.</li><li>A Search Refinement named <em>Newness</em> is correctly configured for the Clothing category.</li></ul>When a merchandiser views the Clothing category, the Search Refinement appears and Works as expected. However, the merchandiser does not see the Search Refinement when searching for Clothing via the Storefront search. What is the Reason?", "There are conflicting Search Refinement definitions for Clothing and one of its parent categories", "The Search Refinement definition is not set up for the Women category", "The Search Refinement definition is not set up for the New Arrivals Category.", "The Search Refinement definitions is not set up for the Root Category");
  quiz[85] = new Question("86. Given the customer basket described below:<br/><ul><li>A customer has an existing basket that consists of multiple items.</li><li>One of the items is identified as a gift ítem by an attribute at the product line ítem.</li></ul>The developer needs to write custom code to fetch the customer basket and then modify the basket based upon the items in the cart. If the basket contains any gift items, modify the basket and create a separate shipment for the gift item. Four hooks are required to make the modification, beginning with modifyGETRespone and ending with validatebasket.<br/><ul><li>Dw.ocapi.shop.basket.modifyGETResponse.</li><li>-- missing hook –</li><li>-- missing hook --</li><li>dw.ocapi.shop.basket.validateBasket.</li></ul>What are the two missing hooks in the middle?", "dw.ocapi.shop.basket.shipment.beforePATCH<br/>dw.ocapi.shop.baskep.shopment.beforePOST", "dw.ocapi.shop.basket.shipment.afterDELETE<br/>dw.ocapi.shop.basket.shipment.beforePATCH", "dw.ocapi.shop.basket.shipment.beforeDELETE<br/>dw.ocapi.shop.baskep.shopment.beforePOST", "dw.ocapi.shop.baskep.shopment.beforePOST<br/>dw.ocapi.shop.baskep.shopment.beforePUT");
  quiz[86] = new Question("87. A merchant has a requirement to render personalized content to n a category page via a Content Slot that targets VIP high-spending customers during a specific promotional period. Which two items should the developer create to achieve the specified requirements? Choose 2 answers:", " VIP Customer Group <br/> Slot Configuration <br/>", "Page Template <br/>Rendering Template", "Rendering Template<br/>VIP Customer Group", "VIP Customer Group<br/>Page Template");
  quiz[87] = new Question("88. Given the following conditions:<br/><ul><li>Site export file with a copy of the Storefront data for a custom site.</li><li>Sandbox with the custom site code, but no Storefront data.</li><li>Requirement for a working copy of SFRA for development reference.</li></ul>A developer is assigned the following Business manager tasks:<br/><ul><li>A. Import the custom Site using Site Import/Export.</li><li>B. Import the SFRA Demo Sites using Site Import/Export.</li><li>C. Rebuild the custom Site search indexes.</li></ul>In what sequence should the developer perform the tasks, so that the custom Site displays the products as intended?", "Task B, then A, then C", "Task A, then C, then B", "Task B, then C, then A", "Task A, then B, then C");
  quiz[88] = new Question("89. A developer is given a task to implement a new Page Designer layout component that doesn't accept certain asset components. How should the developer achieve the above task?", "Add component_type_Exclusions in the layout json configuration", "Add component_type_inclusion in the layout json configuration", "Add layout_type_inclusion in the target components json configurations.", "Add layout_type_exclusion in the other asset components json configuration.");
  quiz[89] = new Question("90. The developer created a new Storefront category in <em>storefront-catalog-m-en</em>, but when viewing the Storefront site, the category is not visible. What are two possible reasons?", "The category does not contain available products <br/> The category is offline. <br/>", "The category is offline. <br/>The Storefront catalog is offline", "The category is not sorted <br /> The Storefront catalog is offline", "The category is not sorte <br /> The category does not contain available products");
  quiz[90] = new Question("91. A client sells its product in single-brand stores as well as in multi-brand stores. When shown in the store locator list, the client wants the single-brand stores to have a particular background color to highlight them. Which Business Manager action should be completed to allow the developer to apply different styling to the single-brand stores?", "Add a Boolean custom attribute to the Store system object", "Configure the existing Store custom object type definition", "Create a new SingleBrandStore custom object configuration.", "Adjust the relevant Site Preference in the Stores group");
  quiz[91] = new Question("92. A developer wants to add a link to the My Account Page. What is the correct code to accomplish this?", "< a href='${URLUtils.url('Account-Show')}>${Resource.msg('myaccount','account',null)}</a>", "< a href='${URLUtils.get('AccountShow')}' >${Resource.msg('myaccount','account',request.locale())}< /a >", "< a href='${url.get('Account-Show')}' >${Resource.message('myaccount')}< /a >", "< a href='${URLUtils ('AccountShow')}' >${ResourceMgr.getPropierties('myaccount','account',null)}< /a >");
  quiz[92] = new Question("9.3 Given a <em>NewsletterSubscription</em> custom object that has a key attribute named email of type String, what is the correct syntax to create the <em>NewsletterSubscription</em> custom object and persist it to the database?", "var customobject = dw.object.CustomObjectMgr. createCustomObject ('NewsletterSubscription', newsLetterForm.email.value);", "var customobject = dw.object.CustomObjectMgr.createNewsletterSubscription('email', newsLetterForm.email.value);", "var customobject = dw.object.CustomObjectMgr.createCustomObject(newsletterForm.email.value, 'NewsletterSubscription');", "var customobject = dw.object.CustomObjectMgr. createCustomObject ('NewsletterSubscription','email', newsLetterForm.email.value);");
  quiz[93] = new Question("94. A developer must configure permissions for an Open Commerce API resource on a sandbox instance that currently does not have any permissions configured. Which two configuration properties are required to enable Access to the resource?. Choose 2 answers.", "Resource_id <br/> Client_id", "Read_attributes <br/> Resource_id", "version_range, <br/> Resource_id", "version_range <br/> version_id");
  quiz[94] = new Question("95. A developer is importing edits for two different sites into the same sandbox, and is provided with four different files. Which two XML files should the developer import using the site-specific Merchant Tools import modules, instead of the Administration section import modules? Choose 2 answers.", " Search Settings in (search and Sites) <br/> Promotions ( in sites and online marketing) <br/>", "System type extensions (Sites only) <br/> Search Settings in (search and Sites)", "Site Jobs (sites) <br/> Search Settings in (search and Sites)", "Search Settings in (search and Sites) <br/> Search rebuilds");
  quiz[95] = new Question("96. In order to build the SFRA code to a developer sandbox for the first time, which build steps should the developer perform for the site to appear and function as designed?", "npm run compile:js, npm run compile:scss, npm run compile:fonts", "npm run compile:js, npm run compile:html, npm run clean", "npm run compile:scss, npm run compile:html, npm run clean", "npm run compile:js, npm run compile: scss, npm run compile:html");
  quiz[96] = new Question("97. A client uses tax tables in Business Manager to calculate tax. They recently started shipping to a new country, Italy, and the tax is not being calculated correctly on the Storefront. What is the likely problem?.", "Tax Jurisdiction is missing", "Tax Region is configured wrong.", "Tax Country is missing", "Tax Locale is configured wrong");
  quiz[97] = new Question("98. A developer wants to use an external application to manage their stores information (such as opening hours, and so on), and see their changes in their B2C Commerce Staging instance as son as they are saved. What is the appropriate technique the developer should perform to allow the merchant to create a new store in this scenario?", "A PUT request to the Stores Data OCAPI.", "A POST request to the Stores Data OCAPI.", "A PATCH request to the Stores Data OCAPI.", "An UPDATE request to the Stores Data OCAPI.");
  quiz[98] = new Question("99. Given the requirements: <ul><li>To show the washing instructions for a clothing product on a dedicated section the detail page.</li><li>Washing instructions come from the product information manager (PIM).</li><li>To have this attribute available to localize in the Storefront.</li></ul>Which action meets these requirements?", "Set the custom attribute as localizable", "Set the product system object type as localizable", "Add a resource file for every locale for which the attribute needs to be translated.", "Add a custom attribute for each locale");
  quiz[99] = new Question("100. A merchant wants customers to be able to order gift vouchers via their site. Since they can issue an unlimited number of these digital vouchers, this item should be available to sell at all items. How can a developer use Business Manager to ensure that the gift vouchers are always available?", "Check the perpetual flag in the product inventory record", "Check the Available to Sell (ATS) flag door the product set", "Set StockLevel = maxAllocation for the product.", "Manually set the inventory to a high number.");
  quiz[100] = new Question("101. A developer wants to create in Business Manager extension with the cartridge named <em>plugin_vm_extension</em>. Which two steps should the developer take for the extension option to show up in Business Manager?. Choose 2 answers:", "Add plugin_bm_extension to the cartridge path under business manager cartridge site <br/> Activate a new code version for the Business Manager Site.", "Add the appropiate roles and permission to the user to view the business manager extension. <br/>Add plugin_bm_extension to the cartridge path under Storefront cartridge site path", "Add plugin_bm_extension to the cartridge path under Storefront cartridge site path. <br/>Add plugin_bm_extension to the cartridge path under business manager cartridge site", "Add plugin_bm_extension to the cartridge path under business manager cartridge site <br/> Add the appropiate roles and permission to the user to view the business manager extension.");
  quiz[101] = new Question("102. A developer is asked to improve the maintainability of a page by reducing its code repetition. What are two techniques the developer should implement to achieve this? Choose 2 answers.", "Use local template includes <br/> Implement template decorators paired with replace tags", "Use local template includes <br/>Require and render templates with < isscript > tags", "Embed partial files using ISML expressions <br/> Require and render templates with < isscript > tags", "Require and render templates with < isscript > tags <br/> Embed partial files using ISML expressions");
  quiz[102] = new Question("103. To ensure SFRA best practices and protect against request forgery, the developer introduced CSRF token generation in the customer address form: <br/><br/><pre>< form … action = 'submit' ><br/> < input name ='${dw.web.CSRFProtection.getTokenName()}' value = '${dw.web.CSRFProtection.generateToken()' ><br/>  … <br/> < the rest of the Form fields ><br/> …<br/>< /form ></pre><br/>To implement CSRF protection when the form is submitted, the developer needs to introduce the CSRF validation using one or both of these methods as applicable: <em>validateRequest</em>, <em>validateAjaxRequest</em>. Where in the code does the developer need to add this CSRF validation check?", "In the middleware chain of the controller post route", "In the controller function that displays the form", "In the controller function that handles the submitted form", "In the model function that persists the form data");
  quiz[103] = new Question("104. A developer has a sandbox configured with a service and its profile and credential. Now there is a requirement to allow changes to the service URL manually from the sandbox. Which B2C feature should the developer use to achieve the request?", "Use the service credential URL field", "Use the service status area, set the override URL checkbox, and then populate the URL field with the required one.", "Use a Sitepreference dedicated for the service URL", "Use a Globalpreference dedicated for the service URL");
  quiz[104] = new Question("105. When inspecting the weekly service status report for a critical internally hosted web service used in the application, a developer notices that there are too many instances of unavailability. Which two solutions can reduce the unavailability of the service? Choose 2 answers.", "Increase the web service time out <br/> Change the code that sets the throwOnError attribute of the service to be true. <br/>", "Update the service to have a faster response time. <br/> Increase the web service time out", "Modify the code that makes the request to the external service to be wrapped in a try/catch block. <br/> Increase the web service time out", "Increase the web service time out <br/> Modify the code that makes the request to the external service to be wrapped in a if else block");
  quiz[105] = new Question("106. A merchant has a requirement to sell a combination of four existing products with a unique product ID. This collection will be known as <em>'Our Top Combo'</em>, and is base on the merchant's trading information that shows this combination to be in high demand. What does the developer need to do next to fulfill this requirement?", "Create a unique product to called 'Our Top Combo' and add the four products into the Product Bundles tab.", "Create a Content Slot with Content Type = Product and add the four component products into that slot.", "Create a Product Set called 'Our Top Combo' and add the products into the set.", "Create a recommendation rule associating the four products as a recommendation group.");
  quiz[106] = new Question("107. A Newsletter controller contains the following route: <br/><br/><pre>Server.post('Subscribe', function (req,res,next){<br/>var newsletterForm = server.forms.getForm('newsletter');<br/>var CustomObjectMgr = require('dw/object/CustomObjectMgr');<br/>if(newsletterForm.valid){<br/> try{<br/>  var CustomObject =   CustomObjectMgr.createCustomObejct('NewsletterSubscription', newsletterform.email.value);<br/>  CustomObject.custom.firstName = newsletterForm.fname.value;<br/>  CustomObject.custom.lastName = newsletterForm.lname.value;-<br/> } catch(e) {<br/>  //Catch error here<br/> }<br/>}<br/>next();<br/>});</pre><br/><br/> Assuming the Custom Object metadata exists, why does this route fail to render the newsletter template when the subscription form is correctly submitted?", "The Custom Object creation is not wrapped in a Transaction.", "Custom Objects can only be created by Job scripts", "The Subscribe route is missing the server.middleware.httpt middleware.", "The CustomObjectMgr variable should be declare outside of the route.");
  quiz[107] = new Question("108. Which three configuration does a developer need to ensure to have a new product visible in the Storefront?", "The Storefront catalog that contains the product is assigned to a site <br/> The product is online and searchable <br/> The search index is built.", "The product has a Price <br/> The search index is built. <br/> The Storefront catalog that contains the product is assigned to a site", "The product has a master product <br/> The search index is built. <br/> The Storefront catalog that contains the product is assigned to a site", "The search index is built. <br/> The Storefront catalog that contains the product is assigned to a site <br/> The search index is built.");
  quiz[108] = new Question("109. Which two items are appropriate content of custom logs implemented at checkout? Choose 2 answers:", "Order failure information <br/> Payment gateway service response code", "Customer's password at post-checkout sign up <br/> Order failure information", "Transaction's credit card information <br/> Payment gateway service response code", "Payment gateway service response code <br/> Customer's password at post-checkout sign up");
  quiz[109] = new Question("110. A developer is writing a server side script that needs to maintain state across calls. The persistent information needed includes these items.<ul><li>The current customer.</li><li>Whether or not the customer is authenticated.</li><li>The privacy attributes (such as tracking consent or cookie policy).</li></ul>Which technique should the developer use to maintain state in an efficient and scalable manner that follows best practice?", "Use the Session class in the B2C Commerce api.", "Use a non-replicable Custom Object to store the information temporarily.", "Use an SFRA controller, because it runs server-side, the state is automatically maintained", "Use a client-side cookie to store the information for the session duration.");
  quiz[110] = new Question("111. A developer working on a simple web service integration is asked to add appropriate logging to allow future troubleshooting. According to logging best practices, which code should the developer write to log when an operation succeeds, but has an unexpected outcome that may produce side effects?", "Logger.warn('Unexpected service response')", "Logger.info('Unexpected service response')", "Logger.debug('Unexpected service response')", "Logger.error('Unexpected service response')");
  quiz[111] = new Question("112. Which three operations should be done in a controller? Choose 3 answers.", "Generate the response as JSON or HTML <br/> Use middleware functions when applicable <br/> Use the model needed for the view.", "Use the Script API to generate data for the view. <br/> Generate the response as JSON or HTML <br/>Create a plain JavaScript object representing a system object", "Create a plain JavaScript object representing a system object <br/>Generate the response as JSON or HTML<br/>Use the model needed for the view.", "Use the model needed for the view.<br/>Create a plain JavaScript object representing a system object <br/>Use middleware functions when applicable");
  quiz[112] = new Question("113. A Storefront is designed so that multiple pages share a common header and footer layout. Which ISML tag should a developer use on the templates for these pages to avoid code repetition in the most effective way?", "< isdecorate > … < / isdecorate >", "< iscontent > … < / iscontent >", "< isreplace > … < / isreplace >", "< isinclude> … </isinclude>");
  quiz[113] = new Question("114. A retailer notices that the Account Addresses page is showing the wrong shopper's address. Which tool should the developer start with to identify the issue?", "Storefront Toolkit", "Pipeline profiler", "Code Profiler", "Reports and Dashboards Module");
  quiz[114] = new Question("115. A client has two B2C Commerce sites in the same instance: one for the U.S market, the other for the European market. The products they make are sold with different safety certificates based-on the world location. For example, they sell a smartphone with certificate A in the U.S and certificate B in Europe, a hairdryer with certificate C in the U.S and certificate D in Europe, and more. How should a developer allow the merchant to display the appropriate certification logo in the produce to details page, depending on the customer's location?", "Add a Site-specific custom attribute to the Product system object type.", "Add a Localizable custom attribute to the Certificate system object type.", "Add and Image custom preference to the Sitepreference system object type", "Add a Localizable custom preference to the SitePreference system object type.");
/* function myFunction(id, question, rightAnswer, wrongAnswer1, wrongAnswer2, wrongAnswer3) {
  quiz[id] = new Question(question, rightAnswer, wrongAnswer1, wrongAnswer2, wrongAnswer3);
} */

document.addEventListener("DOMContentLoaded", function (event) {
  btnProvideQuestion();
});

function Question(question, rightAnswer, wrongAnswer1, wrongAnswer2, wrongAnswer3) {
  this.question = question;
  this.rightAnswer = rightAnswer;
  this.wrongAnswer1 = wrongAnswer1;
  this.wrongAnswer2 = wrongAnswer2;
  this.wrongAnswer3 = wrongAnswer3;
};

function shuffle(o) {
  for (let j, x, i = o.length; i; j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
  return o;
};

function btnProvideQuestion() {
  console.log(quiz);
  let randomNumber = Math.floor(Math.random() * quiz.length);
  //randomQuestion = quiz[randomNumber]; //getRandomQuestion
  randomQuestion = quiz[114]; //getQuestionID
  answers = [randomQuestion.rightAnswer, randomQuestion.wrongAnswer1, randomQuestion.wrongAnswer2, randomQuestion.wrongAnswer3];
  shuffle(answers);
  document.getElementById("question").innerHTML = randomQuestion.question;
  document.getElementById("answerA").value = answers[0];
  document.getElementById("answerA").innerHTML = answers[0];
  document.getElementById("answerB").value = answers[1];
  document.getElementById("answerB").innerHTML = answers[1];
  document.getElementById("answerC").value = answers[2];
  document.getElementById("answerC").innerHTML = answers[2];
  document.getElementById("answerD").value = answers[3];
  document.getElementById("answerD").innerHTML = answers[3];
}

function answerA_clicked() {
  let answerA = document.getElementById("answerA").value;
  checkAnswer(answerA);
}

function answerB_clicked() {
  let answerB = document.getElementById("answerB").value;
  checkAnswer(answerB);
}

function answerC_clicked() {
  let answerC = document.getElementById("answerC").value;
  checkAnswer(answerC);
}

function answerD_clicked() {
  let answerD = document.getElementById("answerD").value;
  checkAnswer(answerD);
}

function adjustScore(isCorrect) {
  if (isCorrect) {
    currentScore++;
  } else {
    if (currentScore > 0) {
      currentScore--;
    }
  }
  document.getElementById("score").innerHTML = currentScore;
}

function checkAnswer(answer) {
  if (answer == randomQuestion.rightAnswer) {
    document.body.classList.add('success');
    adjustScore(true);
    setTimeout(() => {
      document.body.classList.remove('success');
      btnProvideQuestion();
    }, 1000);
  } else {
    document.body.classList.add('error');
    setTimeout(() => {
      document.body.classList.remove('error');
    }, 1000);
  }
}
